services:
  syncthing:
    container_name: ${CONTAINER_NAME}
    image: linuxserver/syncthing:latest
    restart: always
    hostname: ${CONTAINER_HOSTNAME}
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TIME_ZONE}
      - HOME=/data
    volumes:
      - ${DATA_PATH_CONFIG}:/config
      - ${DATA_PATH_DATA}:/data
    network_mode: host
    labels:
      createdBy: "Apps"
