services:
  dameng:
    container_name: ${CONTAINER_NAME}
    image: sizx/dm8:1-3-12-2023.04.17-187846-20040-ENT
    restart: always
    environment:
      - SYSDBA_PWD=${SYSDBA_PASSWORD}
      - UNICODE_FLAG=1
      - LENGTH_IN_CHAR=1
      - CASE_SENSITIVE=0
      - CHARSET=1
      - PAGE_SIZE=32
    volumes:
      - '${DATA_PATH_DATA}:/home/dmdba/data'
    ports:
      - '${DATABASE_PORT}:5236'
    networks:
      - 1panel-network
    labels:
      createdBy: "Apps"

networks:
  1panel-network:
    external: true
